apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: demo-voting-app
# Pod has containers , if Service i would have ports
# goto docker images and find example voting app image
# https://github.com/bfirsh/example-voting-app
# image exposes at port 6379  in memory database port
spec:
  containers:
    - name: postgres
      image: postgres:9.4

      ports:
        - containerPort: 5432

