apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
# Pod has containers , if Service i would have ports
# goto docker images and find example voting app image
# https://github.com/bfirsh/example-voting-app
# image exposes at port 80
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote

      ports:
        - containerPort: 80

